version: "3.8"

services:
  localstack:
    image: localstack/localstack:1.4
    ports:
      - "4566:4566"  # endpoint único
      - "4571:4571"
    environment:
      - SERVICES=s3,sqs,dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
